### ISSUE TITLE
Make doesn't compile

### ISSUE THREAD

**Issue by Ayymoose** [mojobojo/LADX-Disassembly#12]
I'm new to this disassembly project but when I run `make` it gives me an error:

Error: file not found (../../Zelda.gbc)Makefile:25: recipe for target 'bin/banks/bank_00_0.bin' failed

Is there more to this than simply running `make`?

**Comment by kemenaran** [comment]
Yes : for now some resources extracted from the original rom are still needed.

In practice, you'll need to find the ROM _"Legend of Zelda, The - Link's Awakening DX (U) (V1.0) [C][!].gbc"_ (see the checksum in the README file), rename it to `Zelda.gbc` and put it in the root directory of the projet. Then relaunch `make`, and everything should work properly.

**Comment by kemenaran** [comment]
@Ayymoose I just opened a [pull request](https://github.com/mojobojo/LADX-Disassembly/pull/13) that adds better instructions to the README, and better error messages when `zelda.gbc` is missing.

**Comment by Ayymoose** [comment]
@kemenaran  Thanks. A little off topic but I saw your article on Special effects of LADX (https://kemenaran.winosx.com/posts/special-effects-in-zelda-links-awakening/) and I'm really interested in how the other effects are achieved in the game. I was wondering if you are still writing your article?

**Comment by kemenaran** [comment]
I still have a draft that walks through the structure of the main render loop – but it needs some work, and some additional disassembling. And it's more about the code general structure, and not directly related to special rendering effets.

That said I may revisit others effects in the future ; some interesting code should be pretty easy to find with the (partial) disassembly.
