### ISSUE TITLE
Makefile does not compile on Windows

### ISSUE THREAD

**Issue by Rapid-f** [mojobojo/LADX-Disassembly#40]
Hello, I'm a beginner to disassembling as well as using GitHub so I'm sorry if this issue is not very well written.

Typing ``make all`` into the command prompt results in the following errors:

File not found - *.asm
File not found - *.png
rgbasm -E -i src/ -o src/main.o src/main.asm
error: Unable to open incbin file 'gfx/characters/link_1.dmg.2bpp'
make: *** [src/main.o] Error 1

Here is a list of things I've tried to resolve the issue, sorted from most prevalent to least prevalent:
-  replacing the ``shell`` command (used for the ``asm_files`` and ``gfx_files`` variables) with the ``bash`` command in the makefile resulted in resolving the "file not found" errors however it still would not compile due to the RGBDS error.
- I found out the gfx.py script was not working due to missing modules, however that has now been resolved and, even when combined with the bash fix mentioned previously, the makefile still does not work.
- I've used three different versions of make - nmake (gave a different error due to syntax differences), GnuWin32, and Cygwin (both gave the same errors).
- I've tried removing make from my system's Path, and then copying make directly to the folder - same error.

OS: Windows 10
Programs used:
- Python 3.6.4
- Python 2.7.14 (the system Path directs to this version of Python, not 3.6.4)
- Git 2.10.2.windows.1
- Make 3.81 (GnuWin32)
- RGBDS 0.3.6

**Comment by Rapid-f** [comment]
1. It is not.
2. Yes, so long as I correct your typo ;)
3. It outputs the following:
src/gfx/cgb_misc.png
src/gfx/characters/link_1.cgb.png
src/gfx/characters/link_1.dmg.png
src/gfx/characters/link_2.cgb.png
src/gfx/characters/link_2.dmg.png
src/gfx/characters/nightmare.cgb.png
src/gfx/characters/nightmare.dmg.png
src/gfx/characters/npc_1.cgb.png
src/gfx/characters/npc_1.dmg.png
src/gfx/characters/npc_2.cgb.png
src/gfx/characters/npc_2.dmg.png
src/gfx/characters/npc_3.cgb.png
src/gfx/characters/npc_3.dmg.png
src/gfx/characters/npc_4.cgb.png
src/gfx/characters/npc_4.dmg.png
src/gfx/ending/ending.cgb.png
src/gfx/ending/ending.dmg.png
src/gfx/fonts/font.cgb.png
src/gfx/fonts/font.dmg.png
src/gfx/fonts/font_large.cgb.png
src/gfx/fonts/font_large.dmg.png
src/gfx/intro/canopy.cgb.png
src/gfx/intro/clouds-bottom.cgb.png
src/gfx/intro/clouds-bottom.dmg.png
src/gfx/intro/clouds-middle.cgb.png
src/gfx/intro/clouds-middle.dmg.png
src/gfx/intro/clouds-top.cgb.png
src/gfx/intro/clouds-top.dmg.png
src/gfx/intro/copyright.cgb.png
src/gfx/intro/egg.cgb.png
src/gfx/intro/egg_top.cgb.png
src/gfx/intro/intro.cgb.png
src/gfx/intro/intro.dmg.png
src/gfx/intro/link_pic.cgb.png
src/gfx/intro/marin.cgb.png
src/gfx/intro/mountain.cgb.png
src/gfx/intro/mountain_clouds.cgb.png
src/gfx/intro/palm_trees.cgb.png
src/gfx/intro/sand.cgb.png
src/gfx/intro/seafoam.cgb.png
src/gfx/intro/seafoam_animation.cgb.png
src/gfx/intro/title.cgb.png
src/gfx/intro/title.dmg.png
src/gfx/intro/unused_1.cgb.png
src/gfx/intro/unused_2.cgb.png
src/gfx/intro/waves.cgb.png
src/gfx/intro/waves.dmg.png
src/gfx/intro/waves_animation.cgb.png
src/gfx/items/instruments.cgb.png
src/gfx/items/instruments.dmg.png
src/gfx/items/items_1.cgb.png
src/gfx/items/items_1.dmg.png
src/gfx/items/items_2.cgb.png
src/gfx/items/items_2.dmg.png
src/gfx/menus/menu.cgb.png
src/gfx/menus/menu.dmg.png
src/gfx/menus/print.png
src/gfx/photos/photo_bow_wow.png
src/gfx/photos/photo_bridge.png
src/gfx/photos/photo_dizzy_link.png
src/gfx/photos/photo_elements_1.png
src/gfx/photos/photo_elements_2.png
src/gfx/photos/photo_elements_3.png
src/gfx/photos/photo_fisherman.png
src/gfx/photos/photo_ghost.png
src/gfx/photos/photo_kanalet.png
src/gfx/photos/photo_mabe.png
src/gfx/photos/photo_marin_cliff.png
src/gfx/photos/photo_marin_well.png
src/gfx/photos/photo_nice_link.png
src/gfx/photos/photo_shop.png
src/gfx/photos/photo_ulrira.png
src/gfx/photos/photo_zora.png
src/gfx/scenes/christine.cgb.png
src/gfx/scenes/christine.dmg.png
src/gfx/scenes/marin_beach.cgb.png
src/gfx/scenes/marin_beach.dmg.png
src/gfx/scenes/painting.cgb.png
src/gfx/scenes/painting.dmg.png
src/gfx/scenes/relief.cgb.png
src/gfx/scenes/relief.dmg.png
src/gfx/world/animated_tiles.w32.cgb.png
src/gfx/world/animated_tiles.w32.dmg.png
src/gfx/world/camera_shop.cgb.png
src/gfx/world/camera_shop.dmg.png
src/gfx/world/color_dungeon.png
src/gfx/world/dungeons.cgb.png
src/gfx/world/dungeons.dmg.png
src/gfx/world/minimap.cgb.png
src/gfx/world/minimap.dmg.png
src/gfx/world/overworld_1.cgb.png
src/gfx/world/overworld_1.dmg.png
src/gfx/world/overworld_2.cgb.png
src/gfx/world/overworld_2.dmg.png

I'd like to let you know that I got the makefile semi-working so long as I convert all the png files manually via ``python tools/gfx.py 2bpp $(find src/gfx -type f -name '*.png')`` before proceeding to ``make all``. The catch here is that I get the following error:

rgbasm -E -i src/ -o src/main.o src/main.asm
rgblink -O Zelda.gbc -n game.sym -m game.map -o game.gbc src/main.o
rgbfix  -c -n 0 -r 0x03 -s -l 0x33 -k "01" -m 0x1B -j -p 0xFF -t "ZELDA" -v game.gbc
game.gbc: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
make: *** [game.gbc] Error 1

Upon opening the ROM in BGB it works without fault, however. Even the labeling in the debugger seems to work fine.

**Comment by Rapid-f** [comment]
Your first test resulted in this output (both versions of the makefile):

GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-pc-mingw32
Reading makefiles...
File not found - *.asm
File not found - *.png
Updating goal targets....
 File `src/main.o' does not exist.
Must remake target `src/main.o'.
rgbasm -E -i src/ -o src/main.o src/main.asm
error: Unable to open incbin file 'gfx/characters/link_1.dmg.2bpp'
make: *** [src/main.o] Error 1

With the updated script, `make all` still results in the same error mentioned in the issue, even with the `asm_files = $(bash find src -type f -name '*.asm'); gfx_files = $(bash find src/gfx -type f -name '*.png')` fix I've mentioned.

**Comment by mojobojo** [comment]
For building under windows may I suggest using cygwin or mingw? Early on I was building mostly on windows and I was using one of those. The MD5 error happens to me as well. Differences in the file as follows

```
~/LADX-Disassembly $ cmp -l Zelda.gbc game.gbc | gawk '{printf "%08X %02X %02X\n", $1, strtonum(0$2), strtonum(0$3)}'
0000014F E3 E4
00000150 FD 10
0000824E D0 D1
0000960C 20 21
00009816 02 03
0000981D 20 21
000098F5 38 39
00009D77 5E 5F
0000A817 68 69
00010378 40 41
0001118C 78 79
000111A4 38 39
000111AC 88 89
000111AE 88 89
000111BC 20 21
000111E2 88 89
00011EF9 7E 7F
00011EFD 11 12
000120D1 3E 3F
00012EFA 6F 70
00012EFE 70 71
```

**Comment by Rapid-f** [comment]
I just tried MinGW and got the same error. I have tried Cygwin but I only installed the Devel package for make. Is there anything I'm doing wrong in that regard? I've never fiddled with these environment installers before.

This is what my system Path looks like for MinGW:

C:\MinGW\msys\1.0\bin
C:\MinGW\bin
C:\MinGW\lib\gettext
C:\MinGW\msys\1.0\sbin\awk
C:\MinGW\msys\1.0\sbin

**Comment by mattcurrie** [comment]
Hi folks, have identified an issue (rednex/rgbds/issues/259) in rgbds 0.3.6 which causes off by one errors with some ```jr``` instructions. Looks like you might be running into that problem.  Downgrade to rgbds 0.3.5 should work for now.

**Comment by Rapid-f** [comment]
@mattcurrie Yup that works wonders.

Looks like installing MinGW worked. I found out that the errors were due to how my system Path was set up. Case in point: move the MinGW paths to the top. Thanks for your help everyone!
