### ISSUE TITLE
Disassemble the maps data

### ISSUE THREAD

**Issue by kemenaran** [mojobojo/LADX-Disassembly#58]
Maps data location has been documented in other projects. It consists of:

- Three base maps (overworld, underworld, side-scrolling views) ;
- Room pointers tables (mapping rooms indices to actual room data) ;
- Room data, defining the base map template, the room objects, and several room metadatas.

The code for parsing and loading the map data has been partially [reverse-engineered](https://github.com/mojobojo/LADX-Disassembly/pull/57) and documented to a good extend (see for instance `CopyMapToTileMapLoop` in `src/bank0.asm`).

However the map data is still in binary form. It could be mangled into a format [similar to what pokered uses](https://github.com/pret/pokered/blob/master/data/mapHeaders/indigoplateau.asm) : a mix of self-described assembly for data-structures, and bin files for data.

## How

This probably involves writing a Python script to parse the overworld and dungeon map data, and write:

- a readable output for data-structures ;
- bin files for actual data (like map objects).

## Documentation

The best documentation available about the map data format probably lies in the source of the LALE Zelda Level Editor. Other fragments are available on various web pages:

- [LALE](https://github.com/Fatories/LALE) : level editor, notes on maps data format
- [Xkeeper's Link's Awakening depot](xkeeper.net/hacking/linksawakening/): maps tilesets and save format infos
- [Artemis251's Link's Awakening Cache](http://artemis251.fobby.net/zelda/index.php): ROM map, maps data format

**Comment by Xkeeper0** [comment]
You can see some of the junk here, if you'd like:

https://github.com/Xkeeper0/links-awakening-junk

**Comment by kemenaran** [comment]
@Xkeeper0 awesome! I actually wanted to contact you, and ask for the sources of your webpage. Thanks a lot!

I will read the code, and probably port part of it to Python. The plan is to write two separate modules:

- One for parsing the different kinds of map data;
- One for writing the map data back into assembly format.

**Comment by kemenaran** [comment]
Maps are now disassembled into a readable format.

Further work:

- Properly output the Map Headers parsed infos (#63)
- Disassemble Warp data (#64)
